<html>
<head>
    <title>Test ZF</title>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap.css'); ?>

</head>
<header>
    <?php if(Zend_Auth::getInstance()->hasIdentity()){
       echo '<div><a href='.$this->url(array('module' => 'auth', 'controller' => 'auth', 'action' => 'logout')) .">Wyloguj</a> </div>";
    } ?>
</header>

<body>
<div class="content">
    <?php echo $this->layout()->content ?>
</div>
<?php echo $this->placeholder('sidebar') ?>
</body>
</html>