<?php $this->doctype(); ?>
<html>
<head>
    <title>Test ZF</title>
    <?php echo
        $this->headLink()->appendStylesheet($this->baseUrl() . '/css/bootstrap.css');
        $this->headScript()->appendFile($this->baseUrl().'/js/jquery/jquery.js');
        $this->headScript()->appendFile($this->baseUrl().'/js/frontend.js', 'text/javascript');
        echo $this->headLink();
        echo $this->headScript();
    ?>

</head>
<header>
</header>

<body>
<div>

</div>
<div class="container">
    <?php echo $this->layout()->content ?>
</div>
<?php echo $this->placeholder('sidebar') ?>
</body>
</html>