<? return array (
  'Autor' => 'models/testzf/Autor.php',
  'AutorPeer' => 'models/testzf/AutorPeer.php',
  'AutorQuery' => 'models/testzf/AutorQuery.php',
  'AutorTableMap' => 'models/testzf/map/AutorTableMap.php',
  'BaseAutor' => 'models/testzf/om/BaseAutor.php',
  'BaseAutorPeer' => 'models/testzf/om/BaseAutorPeer.php',
  'BaseAutorQuery' => 'models/testzf/om/BaseAutorQuery.php',
  'BaseBook' => 'models/testzf/om/BaseBook.php',
  'BaseBookPeer' => 'models/testzf/om/BaseBookPeer.php',
  'BaseBookQuery' => 'models/testzf/om/BaseBookQuery.php',
  'BaseUser' => 'models/testzf/om/BaseUser.php',
  'BaseUserPeer' => 'models/testzf/om/BaseUserPeer.php',
  'BaseUserQuery' => 'models/testzf/om/BaseUserQuery.php',
  'Book' => 'models/testzf/Book.php',
  'BookPeer' => 'models/testzf/BookPeer.php',
  'BookQuery' => 'models/testzf/BookQuery.php',
  'BookTableMap' => 'models/testzf/map/BookTableMap.php',
  'User' => 'models/testzf/User.php',
  'UserPeer' => 'models/testzf/UserPeer.php',
  'UserQuery' => 'models/testzf/UserQuery.php',
  'UserTableMap' => 'models/testzf/map/UserTableMap.php',
);