<? return array (
  'Autor' => 'models/Autor.php',
  'AutorPeer' => 'models/AutorPeer.php',
  'AutorQuery' => 'models/AutorQuery.php',
  'AutorTableMap' => 'models/map/AutorTableMap.php',
  'BaseAutor' => 'models/om/BaseAutor.php',
  'BaseAutorPeer' => 'models/om/BaseAutorPeer.php',
  'BaseAutorQuery' => 'models/om/BaseAutorQuery.php',
  'BaseBook' => 'models/om/BaseBook.php',
  'BaseBookPeer' => 'models/om/BaseBookPeer.php',
  'BaseBookQuery' => 'models/om/BaseBookQuery.php',
  'BaseUser' => 'models/om/BaseUser.php',
  'BaseUserPeer' => 'models/om/BaseUserPeer.php',
  'BaseUserQuery' => 'models/om/BaseUserQuery.php',
  'Book' => 'models/Book.php',
  'BookPeer' => 'models/BookPeer.php',
  'BookQuery' => 'models/BookQuery.php',
  'BookTableMap' => 'models/map/BookTableMap.php',
  'User' => 'models/User.php',
  'UserPeer' => 'models/UserPeer.php',
  'UserQuery' => 'models/UserQuery.php',
  'UserTableMap' => 'models/map/UserTableMap.php',
);