<?php
// This file generated by Propel 1.7.1 convert-conf target
// from XML runtime conf file /srv/vhosts/testzf/vendor/dafik/generator/schema/testzf/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'testzf' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=test',
        'user' => 'root',
        'password' => 'test',
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
        ),
      ),
    ),
    'default' => 'testzf',
  ),
  'generator_version' => '1.7.1',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-testzf-conf.php');
return $conf;